name: lancamento_contatos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Design
  cupertino_icons: # Ícones Default
  google_fonts: # Fonte customizada
  flutter_platform_alert: # Alert específico de cada plataforma
  date_field: # Campo de Data/Hora
  drop_down_list: # Campo Combobox
  brasil_fields: # Mascaras e Formatos Brasileiros
  # modal_bottom_sheet:      # Bottom Sheet
  table_calendar: # Calendário (can`t upgrade)

  # Util
  localization: # Localizações PT-BR
  intl: # Formatações (can`t upgrade)
  uuid: # Id único
  pdf: # Criação do PDF de relatórios
  share_plus: # Compartilhar Arquivos
  path_provider: # Caminhos do App

  # Database
  hive: # Banco de dados local
  hive_flutter: # Banco de dados local

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: # Boas práticas no Flutter
  hive_generator: # Gerador de adapter para Hive
  build_runner: # Comandos autmatizados
  change_app_package_name: # Alterar package do app facilmente
  flutter_launcher_icons: # Ícones do appß

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo-app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
